server:
  port: 8080

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 2b355d0dcf6e30160bfe72f0783497efbcf5d7c1
>>>>>>> parent of cceb662 (Merge branch 'dev' of https://github.com/hdprojectteam2/bookwithticket into feature/cart)
=======
>>>>>>> parent of 77b3246 (merge feature/member-book into dev)
spring:
  application:
    name: bookwithticket
  datasource:
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/bookwithticket?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MULTI
=======
>>>>>>> parent of cceb662 (Merge branch 'dev' of https://github.com/hdprojectteam2/bookwithticket into feature/cart)
=======
>>>>>>> parent of 77b3246 (merge feature/member-book into dev)
    url: jdbc:h2:mem:bookwithticket;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  #redis
  data:
    redis:
      host: localhost
      port: 6379
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 2b355d0dcf6e30160bfe72f0783497efbcf5d7c1
>>>>>>> parent of cceb662 (Merge branch 'dev' of https://github.com/hdprojectteam2/bookwithticket into feature/cart)
=======
>>>>>>> parent of 77b3246 (merge feature/member-book into dev)
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true