server:
  port: 8787
spring:
  application:
    name: bookwithticket
  datasource:
    url: jdbc:mysql://localhost:3306/bookwithticket?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: multi
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

aladin:
  book:
    api-key: ttbsw01pp1612001
